#!/bin/sh
# Xsetup - run as root before the login dialog appears


if ! [ -e /var/run/etacoser.pid ]; then
	touch /var/run/etacoser.pid
	etacoser
else
	echo "eta-coser found"
fi

#xconsole -geometry 480x130-0-0 -notify -verbose -fn fixed -exitOnFail -file /dev/xconsole &
